[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = [
  "python -m venv --system-site-packages venv",
  "venv/bin/pip install --upgrade pip",
  "venv/bin/pip install -r requirements.txt"
]

[start]
cmd = "venv/bin/python -m uvicorn iape.src.app:app --host 0.0.0.0 --port $PORT"
