[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
cmds = ["pip install -r iape/requirements.txt"]

[start]
cmd = "cd iape && uvicorn src.app:app --host 0.0.0.0 --port $PORT"
